language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  # For some strange reason pip fails on pip install -e .[tests]
  - "pip install pytest==2.9.2"
  - "python setup.py develop"
script:
  - py.test
